const error = require("../middlewares/error");
const log_req = require("../middlewares/log_req");
const log_res = require("../middlewares/log_res");
const cors = require("cors");
const body_parser = require("body-parser");
module.exports = function (app) {
  app.use(log_req);
  app.use(log_res);
  app.use(cors());
  app.use(body_parser.json());
  app.use(body_parser.urlencoded({ extended: true }));
  app.use(require("../middlewares/auth_token"));
  app.use(require("../middlewares/body_validation"));
  app.use("/auth", require("../routes/auth"));
  app.use("/import", require("../routes/import"));
  app.use("/lookup/branches", require("../routes/branches"));
  app.use("/lookup/departments", require("../routes/departments"));
  app.use("/lookup/positions", require("../routes/positions"));
  app.use("/employees", require("../routes/employees"));
  app.use("/notifications", require("../routes/notifications"));
  app.use("/requests", require("../routes/requests"));
  app.use("/att", require("../routes/attendance"));
  app.use("/logger", require("../routes/logger"));
  app.use("/latenes", require("../routes/latenes"));
  app.use("/deduction", require("../routes/deduction"));
  app.use("/empPenalityCounts", require("../routes/empPenalityCounts"));
  app.use("/vacations", require("../routes/vacations"));
  app.use("/officalHolidays", require("../routes/officalHolidays"));
  app.use("/restAllowances", require("../routes/restAllowances"));
  app.use("/jobStatus", require("../routes/jobStatus"));
  app.use(error);
};
